// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY Tapper.Test
// </auto-generated>
#nullable enable
using System;
using System.IO;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Tapper.Tests.SourceTypes;
using Tapper.TypeMappers;
using Xunit;
using Xunit.Abstractions;

namespace Tapper.Tests;

public class CollectionMapTest
{
    private readonly ITestOutputHelper _output;

    public CollectionMapTest(ITestOutputHelper output)
    {
        _output = output;
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldArray()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldArray);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldArray)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldArraySegmentint()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldArraySegmentint);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldArraySegmentint)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldListfloat()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldListfloat);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldListfloat)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldLinkedListstring()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldLinkedListstring);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldLinkedListstring)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldQueueGuid()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldQueueGuid);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldQueueGuid)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldStackUri()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldStackUri);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldStackUri)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldHashSetDateTime()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldHashSetDateTime);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldHashSetDateTime)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldIEnumerablebool()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldIEnumerablebool);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldIEnumerablebool)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldIReadOnlyCollectionbyte()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldIReadOnlyCollectionbyte);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldIReadOnlyCollectionbyte)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldIReadOnlyListobject()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldIReadOnlyListobject);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldIReadOnlyListobject)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldICollectionstring()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldICollectionstring);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldICollectionstring)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldIListbool()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldIListbool);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldIListbool)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionFieldISetsbyte()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionFieldISetsbyte);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionFieldISetsbyte)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }


    [Fact]
    public void Test_ClassIncludeCollectionPropertyArray()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyArray);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyArray)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionPropertyArraySegmentint()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyArraySegmentint);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyArraySegmentint)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionPropertyListfloat()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyListfloat);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyListfloat)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionPropertyLinkedListstring()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyLinkedListstring);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyLinkedListstring)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionPropertyQueueGuid()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyQueueGuid);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyQueueGuid)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionPropertyStackUri()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyStackUri);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyStackUri)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionPropertyHashSetDateTime()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyHashSetDateTime);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyHashSetDateTime)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionPropertyIEnumerablebool()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyIEnumerablebool);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyIEnumerablebool)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionPropertyIReadOnlyCollectionbyte()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyIReadOnlyCollectionbyte);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyIReadOnlyCollectionbyte)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionPropertyIReadOnlyListobject()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyIReadOnlyListobject);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyIReadOnlyListobject)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionPropertyICollectionstring()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyICollectionstring);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyICollectionstring)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionPropertyIListbool()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyIListbool);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyIListbool)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

    [Fact]
    public void Test_ClassIncludeCollectionPropertyISetsbyte()
    {
        var compilation = CompilationSingleton.Compilation;

        var codeGenerator = new TypeScriptCodeGenerator(compilation, Environment.NewLine, 2, false, SerializerOption.Json, NamingStyle.None, EnumStyle.UnderlyingValue, Logger.Empty);

        var type = typeof(ClassIncludeCollectionPropertyISetsbyte);
        var typeSymbol = compilation.GetTypeByMetadataName(type.FullName!)!;

        var writer = new CodeWriter();

        codeGenerator.AddType(typeSymbol, ref writer);

        var code = writer.ToString();
        var gt = CollectionTypeTranspilationAnswer.Dict[nameof(ClassIncludeCollectionPropertyISetsbyte)];

        _output.WriteLine(code);
        _output.WriteLine(gt);

        Assert.Equal(gt, code, ignoreLineEndingDifferences: true);
    }

}
