// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY Tapper.Test
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Tapper.Test.SourceTypes;

namespace Tapper.Tests;

public static class DictionaryTypeTranspilationAnswer
{
    public static Dictionary<string, string> Dict = new();

    static DictionaryTypeTranspilationAnswer()
    {
        Dict[nameof(ClassIncludeDictionaryFieldDictionaryintstring)] = @"/** Transpiled from Tapper.Test.SourceTypes.ClassIncludeDictionaryFieldDictionaryintstring */
export type ClassIncludeDictionaryFieldDictionaryintstring = {
  /** Transpiled from System.Collections.Generic.Dictionary<int, string> */
  FieldOfDictionaryintstring: { [key in number]: string };
}
";
        Dict[nameof(ClassIncludeDictionaryFieldIDictionaryfloatGuid)] = @"/** Transpiled from Tapper.Test.SourceTypes.ClassIncludeDictionaryFieldIDictionaryfloatGuid */
export type ClassIncludeDictionaryFieldIDictionaryfloatGuid = {
  /** Transpiled from System.Collections.Generic.IDictionary<float, System.Guid> */
  FieldOfIDictionaryfloatGuid: { [key in number]: string };
}
";
        Dict[nameof(ClassIncludeDictionaryFieldIReadOnlyDictionaryEnum1DateTime)] = @"/** Transpiled from Tapper.Test.SourceTypes.ClassIncludeDictionaryFieldIReadOnlyDictionaryEnum1DateTime */
export type ClassIncludeDictionaryFieldIReadOnlyDictionaryEnum1DateTime = {
  /** Transpiled from System.Collections.Generic.IReadOnlyDictionary<Tapper.Test.SourceTypes.Enum1, System.DateTime> */
  FieldOfIReadOnlyDictionaryEnum1DateTime: { [key in Enum1]: (Date | string) };
}
";

        Dict[nameof(ClassIncludeDictionaryPropertyDictionaryintstring)] = @"/** Transpiled from Tapper.Test.SourceTypes.ClassIncludeDictionaryPropertyDictionaryintstring */
export type ClassIncludeDictionaryPropertyDictionaryintstring = {
  /** Transpiled from System.Collections.Generic.Dictionary<int, string> */
  PropertyOfDictionaryintstring: { [key in number]: string };
}
";
        Dict[nameof(ClassIncludeDictionaryPropertyIDictionaryfloatGuid)] = @"/** Transpiled from Tapper.Test.SourceTypes.ClassIncludeDictionaryPropertyIDictionaryfloatGuid */
export type ClassIncludeDictionaryPropertyIDictionaryfloatGuid = {
  /** Transpiled from System.Collections.Generic.IDictionary<float, System.Guid> */
  PropertyOfIDictionaryfloatGuid: { [key in number]: string };
}
";
        Dict[nameof(ClassIncludeDictionaryPropertyIReadOnlyDictionaryEnum1DateTime)] = @"/** Transpiled from Tapper.Test.SourceTypes.ClassIncludeDictionaryPropertyIReadOnlyDictionaryEnum1DateTime */
export type ClassIncludeDictionaryPropertyIReadOnlyDictionaryEnum1DateTime = {
  /** Transpiled from System.Collections.Generic.IReadOnlyDictionary<Tapper.Test.SourceTypes.Enum1, System.DateTime> */
  PropertyOfIReadOnlyDictionaryEnum1DateTime: { [key in Enum1]: (Date | string) };
}
";
    }
}
