// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY Tapper.Test.SourceTypes
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Tapper.Test.SourceTypes;

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.

[TranspilationSource]
public class ClassIncludeDictionaryFieldDictionaryintstring
{
    public Dictionary<int, string> FieldOfDictionaryintstring;
}

[TranspilationSource]
public class ClassIncludeDictionaryFieldIDictionaryfloatGuid
{
    public IDictionary<float, Guid> FieldOfIDictionaryfloatGuid;
}

[TranspilationSource]
public class ClassIncludeDictionaryFieldIReadOnlyDictionarystringDateTime
{
    public IReadOnlyDictionary<string, DateTime> FieldOfIReadOnlyDictionarystringDateTime;
}

[TranspilationSource]
public class ClassIncludeDictionaryPropertyDictionaryintstring
{
    public Dictionary<int, string> PropertyOfDictionaryintstring { get; set; }
}

[TranspilationSource]
public class ClassIncludeDictionaryPropertyIDictionaryfloatGuid
{
    public IDictionary<float, Guid> PropertyOfIDictionaryfloatGuid { get; set; }
}

[TranspilationSource]
public class ClassIncludeDictionaryPropertyIReadOnlyDictionarystringDateTime
{
    public IReadOnlyDictionary<string, DateTime> PropertyOfIReadOnlyDictionarystringDateTime { get; set; }
}


#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
