// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY Tapper.Test.SourceTypes
// </auto-generated>
#nullable enable

namespace Tapper.Tests.SourceTypes;

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemBoolean
{
    public System.Boolean FieldOfSystemBoolean;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemByte
{
    public System.Byte FieldOfSystemByte;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemSByte
{
    public System.SByte FieldOfSystemSByte;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemChar
{
    public System.Char FieldOfSystemChar;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemDecimal
{
    public System.Decimal FieldOfSystemDecimal;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemDouble
{
    public System.Double FieldOfSystemDouble;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemSingle
{
    public System.Single FieldOfSystemSingle;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemInt32
{
    public System.Int32 FieldOfSystemInt32;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemUInt32
{
    public System.UInt32 FieldOfSystemUInt32;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemInt64
{
    public System.Int64 FieldOfSystemInt64;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemUInt64
{
    public System.UInt64 FieldOfSystemUInt64;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemInt16
{
    public System.Int16 FieldOfSystemInt16;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemUInt16
{
    public System.UInt16 FieldOfSystemUInt16;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemObject
{
    public System.Object? FieldOfSystemObject;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemString
{
    public System.String? FieldOfSystemString;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemUri
{
    public System.Uri? FieldOfSystemUri;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemGuid
{
    public System.Guid FieldOfSystemGuid;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemDateTime
{
    public System.DateTime FieldOfSystemDateTime;
}

[TranspilationSource]
public class ClassIncludePrimitiveFieldSystemTimeSpan
{
    public System.TimeSpan FieldOfSystemTimeSpan;
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemBoolean
{
    public System.Boolean PropertyOfSystemBoolean { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemByte
{
    public System.Byte PropertyOfSystemByte { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemSByte
{
    public System.SByte PropertyOfSystemSByte { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemChar
{
    public System.Char PropertyOfSystemChar { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemDecimal
{
    public System.Decimal PropertyOfSystemDecimal { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemDouble
{
    public System.Double PropertyOfSystemDouble { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemSingle
{
    public System.Single PropertyOfSystemSingle { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemInt32
{
    public System.Int32 PropertyOfSystemInt32 { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemUInt32
{
    public System.UInt32 PropertyOfSystemUInt32 { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemInt64
{
    public System.Int64 PropertyOfSystemInt64 { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemUInt64
{
    public System.UInt64 PropertyOfSystemUInt64 { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemInt16
{
    public System.Int16 PropertyOfSystemInt16 { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemUInt16
{
    public System.UInt16 PropertyOfSystemUInt16 { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemObject
{
    public System.Object? PropertyOfSystemObject { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemString
{
    public System.String? PropertyOfSystemString { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemUri
{
    public System.Uri? PropertyOfSystemUri { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemGuid
{
    public System.Guid PropertyOfSystemGuid { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemDateTime
{
    public System.DateTime PropertyOfSystemDateTime { get; set; }
}

[TranspilationSource]
public class ClassIncludePrimitivePropertySystemTimeSpan
{
    public System.TimeSpan PropertyOfSystemTimeSpan { get; set; }
}

